### ISSUE TITLE
How to convert DES-EDE2 16 byte key to List<int> with 8 elements.

### ISSUE THREAD

**Issue by gaddlord** [delletenebre/dart_des#11]
The DES constructor checks for

```
if (key.length != 8) {...}
````

I have a 16 bytes key implementation working well on Delphi and C#. How I can convert my 16 elements array of bytes to an acceptable key?

**Comment by oboobortot** [comment]
No issue. I switched from calling DES() to calling DES3() which is the right class for 16-byte keys.
