### ISSUE TITLE
encrypt error

### ISSUE THREAD

**Issue by z234009184** [delletenebre/dart_des#2]
``` dart
DES3 des3CBC = DES3(key: 'PDXDzTttJ1F4lgEsoR4xPB9U'.codeUnits, mode: DESMode.CBC, iv: utf8.encode('OoWrs7by'));
final encryptData = des3CBC.encrypt('{"keyword":"hello","page":"1","userToken":""}'.codeUnits);
String encryptString = base64Encode(encryptData);
print(encryptString);
```

with this code, I get error

@delletenebre 
please help me~  thanks so much!!

**Comment by delletenebre** [comment]
Hello. Try add padding function like here https://github.com/delletenebre/dart_des/issues/1
I'll add padding functions in next release.

**Comment by z234009184** [comment]
> Hello. Try add padding function like here #1
> I'll add padding functions in next release.

Thank for your reply, but after the padding function , server decrypted error, i don't know where wrong.

**Comment by z234009184** [comment]
I found  the `pad()` func was different between PHP and Dart, how to set the pkcs7padding or pkcs5padding?  please help me, thank you so much!!🙏

**Comment by z234009184** [comment]
It's work for me~

``` dart
static List<int> _pad(List<int> data) {
    int left = 8 - (data.length % 8);
    final padding = List.generate(8, (index) => left);
    return data + padding.sublist(0, left);
  }
```
