### ISSUE TITLE
16 byte key doesn't work

### ISSUE THREAD

**Issue by fachri-r** [delletenebre/dart_des#3]
I'm having a problem regarding to the length of the key. At the case that I'm currently working on I have to use 16 byte key, but I keep getting an exception that the key must be 8 byte long even though that I've followed the exact same snippet from the documentation

**Comment by delletenebre** [comment]
Hi. Since encryption is complicated and I'm not an expert, I can't explain why DES use only 8-byte key, sorry :( For 16- or 24-byte keys you should use DES3.

```dart
String key = '1234567812345678'; // 16-byte
String message = 'Driving in from the edge of town';
DES3 des3ECB = DES3(key: key.codeUnits, mode: DESMode.ECB);
encrypted = des3ECB.encrypt(message.codeUnits);
decrypted = des3ECB.decrypt(encrypted);
print('Triple DES mode: ECB');
print('encrypted (hex): ${hex.encode(encrypted)}');
print('decrypted (utf8): ${utf8.decode(decrypted)}');
```

**Comment by fachri-r** [comment]
> Hi. Since encryption is complicated and I'm not an expert, I can't explain why DES use only 8-byte key, sorry :( For 16- or 24-byte keys you should use DES3.
> 
> ```dart
> String key = '1234567812345678'; // 16-byte
> String message = 'Driving in from the edge of town';
> DES3 des3ECB = DES3(key: key.codeUnits, mode: DESMode.ECB);
> encrypted = des3ECB.encrypt(message.codeUnits);
> decrypted = des3ECB.decrypt(encrypted);
> print('Triple DES mode: ECB');
> print('encrypted (hex): ${hex.encode(encrypted)}');
> print('decrypted (utf8): ${utf8.decode(decrypted)}');
> ```

I've tried this but the result remains the same. Thanks anyway

**Comment by fachri-r** [comment]
It seems like in my project this package is colliding with another package that I try, then I've tried to make a new project to test the encryption and it works!
