### ISSUE TITLE
can dart_des 1.0.0 compatible 0.0.2 ?

### ISSUE THREAD

**Issue by kittyzoe** [delletenebre/dart_des#8]
hi sir,

 I'am working on a project that phone communicate with stm32 MCU by bluetooth(BLE) , 
I encrypted byte arrays with dart_des 0.0.2 , it encrypted 8bytes data and got 8bytes encrypted data, I like it because I don't want the encrypted data length got too long,  but now the dart_des 1.0.0 is different, it encrypt 8 bytes data and got 16 bytes data, it's hard to send data to stm32 mcu, so could  I want to know it's possible to compatible with 0.0.2 version and also get null safety feature ? 

Thanks in advance .

kitty

**Comment by delletenebre** [comment]
Hello. Please, try with param `paddingType = DESPaddingType.None`:

`DES des = DES(key: 'any data'.codeUnits, mode: DESMode.ECB, paddingType: DESPaddingType.None);`

**Comment by kittyzoe** [comment]
hi delletenebre,

it works , thanks a lot!
