### ISSUE TITLE
RangeError (index): Invalid value: Not in inclusive range 0..63: 64

### ISSUE THREAD

**Issue by chanreylee** [delletenebre/dart_des#9]
when my sourceStr is Chinese， it will be appeard this error。

mycode

`  
  test("register2", () async {
    var map = "猫";
    String encryptDart = await EncryptUtil.encryptDartDes(map.toString(), "");
    print(encryptDart);
  });

static String encryptDartDes(String srcStr, String dateStr) {
    String keyStr = "12345678";
    final key = keyStr.codeUnits;
    final iv = keyStr.codeUnits;
    DES desCBC = DES(key: key, mode: DESMode.CBC, iv: iv, paddingType: DESPaddingType.PKCS7);

    final encrypted = desCBC.encrypt(srcStr.codeUnits);
    return base64.encode(encrypted);
  }`

errors：
`

dart:core                                               List.[]
package:dart_des/dart_des.dart 1009:27                  DES.xor
package:dart_des/dart_des.dart 1105:19                  DES.crypt
package:dart_des/dart_des.dart 1126:7                   DES.encrypt
package:project_flutter/utils/encrypt_util.dart 46:30  EncryptUtil.encryptDartDes
test\api_test.dart 40:44                                main.<fn>
test\api_test.dart 38:21                                main.<fn>

RangeError (index): Invalid value: Not in inclusive range 0..63: 64

`

**Comment by chanreylee** [comment]
I know the problem， srcStr.codeUnits is UTF-16， but some chars like letters are UTF-8， so it can be。But Chinese is UTF-16， so it can't  be；So, need to translate Chinese to  utf-8 like this:  utf8.encode(srcStr)

**Comment by lijingnan** [comment]
It down：utf8.encode(srcStr)
